2025-05-05 14:27:04,103 ERROR: Exception on /journal/edit_entry [GET] [in /home/venture/.venvs/flask_env/lib/python3.11/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/home/venture/.venvs/flask_env/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venture/.venvs/flask_env/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venture/.venvs/flask_env/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venture/.venvs/flask_env/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venture/.venvs/flask_env/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: edit_entry() missing 1 required positional argument: 'entry_id'
2025-05-05 14:27:50,672 INFO: Digital-Journal-App startup [in /home/venture/journal_app/app/__init__.py:48]
2025-05-05 14:27:53,010 ERROR: Exception on /journal/edit_entry/7 [GET] [in /home/venture/.venvs/flask_env/lib/python3.11/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/home/venture/.venvs/flask_env/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venture/.venvs/flask_env/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venture/.venvs/flask_env/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venture/.venvs/flask_env/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venture/.venvs/flask_env/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venture/journal_app/app/journal/routes.py", line 114, in edit_entry
    return render_template(url_for('journal.edit_entry', entry_id=entry_id))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venture/.venvs/flask_env/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venture/.venvs/flask_env/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venture/.venvs/flask_env/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venture/.venvs/flask_env/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venture/.venvs/flask_env/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venture/.venvs/flask_env/lib/python3.11/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venture/.venvs/flask_env/lib/python3.11/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /journal/edit_entry/7
2025-05-05 14:32:43,118 INFO: Digital-Journal-App startup [in /home/venture/journal_app/app/__init__.py:48]
2025-05-05 14:33:18,175 INFO: Digital-Journal-App startup [in /home/venture/journal_app/app/__init__.py:48]
2025-05-05 14:35:09,063 INFO: Digital-Journal-App startup [in /home/venture/journal_app/app/__init__.py:48]
2025-05-05 14:35:10,884 ERROR: Exception on /journal/edit_entry/7 [GET] [in /home/venture/.venvs/flask_env/lib/python3.11/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/home/venture/.venvs/flask_env/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venture/.venvs/flask_env/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venture/.venvs/flask_env/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venture/.venvs/flask_env/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venture/.venvs/flask_env/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venture/journal_app/app/journal/routes.py", line 114, in edit_entry
    return render_template('journal/edit_entry.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venture/.venvs/flask_env/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venture/.venvs/flask_env/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venture/.venvs/flask_env/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/venture/.venvs/flask_env/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/venture/journal_app/app/templates/journal/edit_entry.html", line 2, in top-level template code
    {% import "bootstrap_wtf.html" as wtf %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venture/journal_app/app/templates/base.html", line 63, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venture/journal_app/app/templates/journal/edit_entry.html", line 7, in block 'content'
    {{ wtf.quick_form_edit(form) }}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venture/.venvs/flask_env/lib/python3.11/site-packages/jinja2/runtime.py", line 784, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venture/journal_app/app/templates/bootstrap_wtf.html", line 130, in template
    {{ form.hidden_tag() }}
  File "/home/venture/.venvs/flask_env/lib/python3.11/site-packages/jinja2/environment.py", line 490, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'form' is undefined
2025-05-05 14:35:33,981 INFO: Digital-Journal-App startup [in /home/venture/journal_app/app/__init__.py:48]
2025-05-05 14:36:03,342 INFO: Digital-Journal-App startup [in /home/venture/journal_app/app/__init__.py:48]
2025-05-05 14:37:14,681 INFO: Digital-Journal-App startup [in /home/venture/journal_app/app/__init__.py:48]
2025-05-05 14:41:08,522 INFO: Digital-Journal-App startup [in /home/venture/journal_app/app/__init__.py:48]
2025-05-05 14:43:16,483 INFO: Digital-Journal-App startup [in /home/venture/journal_app/app/__init__.py:48]
